### ISSUE TITLE
Animator transition duration issue

### ISSUE THREAD

**Issue by SitronX** [SitronX/UnityTimeRewinder#2]
When Animator transition duration is greater than 0, on edge cases animation will get stuck.

**Comment by RootChad** [comment]
Hi, is there a solution to this transition problem?

**Comment by SitronX** [comment]
Hello, i havent had a time to investigate it properly. So there is not really solution for this at the moment. The stuck scenario can happen only when the rewinding ends exactly in the transition. I will try to find solution for this eventually, but i dont really have much free time nowadays. You can help if you feel like it, would appreciate this.
