### ISSUE TITLE
How to pause the game without breaking the time rewind?

### ISSUE THREAD

**Issue by Hatemsla** [SitronX/UnityTimeRewinder#5]
I found information in the documentation that changing Fixed TimeStep or timeScale will lead to a lot of problems, but then how to pause the game? Is it possible to temporarily disable time tracking? Or do something else so that there are no problems with this?

**Comment by SitronX** [comment]
Hello @Hatemsla 
In example scene 1, in latest version i added few buttons on screen that showcase tracking pause, rewind pause and tracking restart. Tracking pause will temporarily stop tracking new values and overwriting buffer, rewind pause will pause the game for tracked attributes (everything that is not tracked will still run normally and is not paused). It depends if you want to pause the game as a whole, or only for a certain tracked objects.

If you want to pause the game as a whole (like when going to the menu), in latest version of this tool, changing timeScale should actually not cause serious issues anymore. There are more safety checks in latest version of this tool than when i wrote this part of documentation. I tested it now, it is actually possible to change timeScale during realtime without issues. So it should be fine to fully pause the game by setting timeScale to 0 and then unpausing by setting 1 again. Thank you for bringing attention to this, i will update it in the documentation.

**Comment by SitronX** [comment]
@Hatemsla  I have just updated this tool to version 2.1, there are few fixes and some changes regarding changing timeScale at runtime. Everything should be working now and documentation is also updated. Please let me know if you will have any issues with this version.

**Comment by Hatemsla** [comment]
Well, it works, and very well. I would like to suggest that you add methods to rewind manager that will allow you to add, delete and find objects to rewind time, since finding such objects only in awake is not always useful, sometimes it is necessary to add new objects, a conditional enemy or a projectile.

**Comment by SitronX** [comment]
@Hatemsla Yep that is good suggestion i will think about adding some proper support for this.

In the meantime, you can use object pooling for this to some degree, where at the start of the game you spawn bunch of disabled projectiles/enemies to the pool and then enable and work with them as you need.
