### ISSUE TITLE
Destroy object

### ISSUE THREAD

**Issue by JSeco181** [SitronX/UnityTimeRewinder#7]
Hello,

I'm using the method for adding new elements for rewind in runtime:

`RewindManager.Instance.AddObjectForTracking(rewindAbstract, RewindManager.OutOfBoundsBehaviour.DisableDestroy);`

At some point of the game, this object is destroyed and I get hte following message:

**MissingReferenceException: The object of type 'PlaneAI_Rewind' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
RewindManager.FixedUpdate () (at Assets/TimeRewinder/TimeRewinderImplementation/Scripts/RewindManager.cs:197)**

Is there a way to handle this behavior? Am I missing something to not track this object anymore?

Maybe can be fixed with something like this?

```
    private  void FixedUpdate()
    {
        if (IsBeingRewinded)
        {
            _rewindedObjects.ForEach(x => x.Rewind(rewindSeconds));

            _lateAddedRewindedObjects.ForEach(x =>
            {
                x.Item1.Rewind(rewindSeconds);

                if (x.Item1.IsManagerTrackingActiveState)
                    x.Item1.RestoreObjectActiveState(rewindSeconds);
            });
        }
        else 
        {
            _rewindedObjects.ForEach(x => x.Track());

            for(int i=0;i<_lateAddedRewindedObjects.Count;i++)
            {
```
                if (_lateAddedRewindedObjects[i].Item1 == null)
                {
                    _lateAddedRewindedObjects.Remove(_lateAddedRewindedObjects[i]);
                    continue;
                }
```

                if (!_lateAddedRewindedObjects[i].Item1.isActiveAndEnabled&& _lateAddedRewindedObjects[i].Item2==OutOfBoundsBehaviour.DisableDestroy)
                {
                    RewindAbstract objectToDestroy = _lateAddedRewindedObjects[i].Item1;
                    _lateAddedRewindedObjects.Remove(_lateAddedRewindedObjects[i]);
                    Destroy(objectToDestroy.gameObject);
                    continue;
                }

                _lateAddedRewindedObjects[i].Item1.Track();

                if (_lateAddedRewindedObjects[i].Item1.IsManagerTrackingActiveState)
                    _lateAddedRewindedObjects[i].Item1.TrackObjectActiveState();
                else if (!_lateAddedRewindedObjects[i].Item1.IsActiveStateTracked)
                {
                    _lateAddedRewindedObjects[i].Item1.IsManagerTrackingActiveState = true;
                    _lateAddedRewindedObjects[i].Item1.TrackObjectActiveState();
                }
            }
  
            if(TrackingEnabled)
                HowManySecondsAvailableForRewind = Mathf.Min(HowManySecondsAvailableForRewind + Time.fixedDeltaTime, HowManySecondsToTrack);
        }
    }
```

Thank you very much!!

**Comment by SitronX** [comment]
Hello @JSeco181 ,
Thank you for mentioning this issue! I cant believe I didnt handle this case 😄 Yes, I like your code snippet. Do you want to make a PR, or should I commit it?

**Comment by JSeco181** [comment]
Hello @SitronX,

Sure, you can commit! no problem 😃

**Comment by SitronX** [comment]
The code is now committed, thanks again :)
